# Add inputs and outputs from these tool invocations to the build variables 
NSC_CUSTOMER_ROOT_DIR = $(EPII_ROOT)/trustzone/nsc_function/nsc_customer
NSC_CUSTOMER_ROOT_SRC_DIR = $(NSC_CUSTOMER_ROOT_DIR)/nsc_src/$(CUSTOMER)
NSC_CUSTOMER_CSRC_DIR = $(NSC_CUSTOMER_ROOT_SRC_DIR)
NSC_CUSTOMER_ASMSRC_DIR = $(NSC_CUSTOMER_ROOT_SRC_DIR)
NSC_CUSTOMER_CUSTOMER_INC_DIR = $(NSC_CUSTOMER_ROOT_DIR)/nsc_inc/$(CUSTOMER)
NSC_CUSTOMER_CXXSRC_DIR = $(NSC_CUSTOMER_ROOT_SRC_DIR)
NSC_CUSTOMER_CCSRC_DIR = $(NSC_CUSTOMER_ROOT_SRC_DIR)
NSC_CUSTOMER_INC_DIR = $(NSC_CUSTOMER_ROOT_DIR)/nsc_inc/$(CUSTOMER)
# extra macros to be defined
NSC_CUSTOMER_DEFINES += -DNSC_$(CUSTOMER)