/*
 * cisdp_cfg.h
 *
 *  Created on: 20240122
 *      Author: 901912
 *
 *      HW5X5
 *      RGB: R = W*H byte, G = W*H byte, B = W*H byte
 *      YUV422: Y= W*H byte, U = ((W*H)>>1) byte, V = ((W*H)>>1) byte
 *      YUV420: Y= W*H byte, U = ((W*H)>>2) byte, V = ((W*H)>>2) byte
 *
 *      JPEG
 *      RAW8(YUV400) x4 Compress = ((613+ (W/16)*(H/16)* 64 + 35) >>2 ) <<2 byte
 *      RAW8(YUV400) x10 Compress = ((613+ (W/16)*(H/16)* 24 + 35) >>2 ) <<2 byte
 *      YUV422 x4 Compress = ((623+ (W/16)*(H/16)* 128 + 35) >>2 ) <<2 byte
 *      YUV422 x10 Compress = ((623+ (W/16)*(H/16)* 50 + 35) >>2 ) <<2  byte
 *      YUV420 x4 Compress = ((623+ (W/16)*(H/16)* 96 + 35) >>2 ) <<2  byte
 *      YUV420 x10 Compress = ((623+ (W/16)*(H/16)* 38 + 35) >>2 ) <<2  byte
 *
 *      CDM
 *      Hot Pixel No Pack + No Meta Data: High= W*H byte, Low= W*H byte, Hot Pixel = W*H byte
 *      Hot Pixel Pack + No Meta Data: High= W*H byte, Low= W*H byte, Hot Pixel = W*H/8 byte
 *      Hot Pixel No Pack + Meta Data: High= W*H byte, Low= W*H byte, Hot Pixel = W*H+3*4+H+W+(H<<1) byte
 *      Hot Pixel Pack + Meta Data: High= W*H byte, Low= W*H byte, Hot Pixel = (W*H>>3)+3*4+H+W+(H<<1) byte
 */

#ifndef APP_SCENARIO_CISDP_CFG_H_
#define APP_SCENARIO_CISDP_CFG_H_

#include "hx_drv_gpio.h"
#include "hx_drv_inp.h"

typedef enum
{
	APP_DP_RES_RGB640x480_INP_SUBSAMPLE_1X,
	APP_DP_RES_RGB640x480_INP_SUBSAMPLE_2X,
	APP_DP_RES_RGB640x480_INP_SUBSAMPLE_4X,
	APP_DP_RES_YUV640x480_INP_SUBSAMPLE_1X,
	APP_DP_RES_YUV640x480_INP_SUBSAMPLE_2X,
	APP_DP_RES_YUV640x480_INP_SUBSAMPLE_4X,
}APP_DP_INP_SUBSAMPLE_E;

#define IMX219_SENSOR_I2CID				(0x10)
#define IMX219_MIPI_CLOCK_FEQ			(456)	//MHz
#define IMX219_MIPI_LANE_CNT			(2)
#define IMX219_MIPI_DPP					(10)	//depth per pixel
#define IMX219_MIPITX_CNTCLK_EN			(1)		//continuous clock output enable
#define IMX219_LANE_NB					(2)
#define SENSORDPLIB_SENSOR_IMX219		(SENSORDPLIB_SENSOR_HM2130)
#define DYNAMIC_ADDRESS

#define IMX219_SENSOR_WIDTH				3280
#define IMX219_SENSOR_HEIGHT			2464
#define IMX219_INP_CROP_WIDTH			3200
#define IMX219_INP_CROP_HEIGHT			2400
#define IMX219_INP_OUT_WIDTH			640
#define IMX219_INP_OUT_HEIGHT			480
#define IMX219_HW2x2_CROP_WIDTH			640
#define IMX219_HW2x2_CROP_HEIGHT		480
#define IMX219_HW5x5_CROP_WIDTH			640
#define IMX219_HW5x5_CROP_HEIGHT		480

#define IMX219_EXPOSURE_DEFAULT			(0x640)
#define IMX219_EXPOSURE_SETTING			(0xA40)
#define IMX219_ANA_GAIN_MIN				0
#define IMX219_ANA_GAIN_MAX				232
#define IMX219_ANA_GAIN_DEFAULT			0x0
#define IMX219_AGAIN_SETTING			(0x40)
#define IMX219_DGTL_GAIN_MIN			0x0100
#define IMX219_DGTL_GAIN_MAX			0x0fff
#define IMX219_DGTL_GAIN_DEFAULT		0x0100
#define IMX219_DGAIN_SETTING			(0x200)

#define IMX219_REG_BINNING_MODE			0x0174
#define IMX219_BINNING_NONE				0x0000
#define IMX219_BINNING_2X2				0x0101
#define IMX219_BINNING_2X2_ANALOG		0x0303
#define IMX219_BINNING_SETTING			(IMX219_BINNING_NONE)

#ifdef TRUSTZONE_SEC
#define EXT_RAM_START   BASE_ADDR_SRAM0_ALIAS
#define MAX_SRAM_ADDR	(BASE_ADDR_SRAM1_ALIAS+1024*1024-1)
#else
#ifndef TRUSTZONE
#define EXT_RAM_START   BASE_ADDR_SRAM0_ALIAS
#define MAX_SRAM_ADDR	(BASE_ADDR_SRAM1_ALIAS+1024*10242-1)
#else
#define EXT_RAM_START   BASE_ADDR_SRAM0
#define MAX_SRAM_ADDR	(BASE_ADDR_SRAM1+1024*1024-1)
#endif
#endif

#define CIS_MIRROR_SETTING			(0x03) //0x00: off/0x01:H-Mirror/0x02:V-Mirror/0x03:HV-Mirror
#define CIS_I2C_ID					IMX219_SENSOR_I2CID
#define CIS_ENABLE_MIPI_INF			(0x01) //0x00: off/0x01: on
#define CIS_MIPI_LANE_NUMBER		(0x02)
#define CIS_ENABLE_HX_AUTOI2C		(0x00) //0x00: off/0x01: on/0x2: on and XSLEEP KEEP HIGH
#define DEAULT_XHSUTDOWN_PIN    	AON_GPIO2

/*
 * DP SENCTRL CFG
 */
#define SENCTRL_SENSOR_TYPE			SENSORDPLIB_SENSOR_IMX219
#define SENCTRL_STREAM_TYPE			SENSORDPLIB_STREAM_NONEAOS
#define SENCTRL_SENSOR_WIDTH 		IMX219_SENSOR_WIDTH
#define SENCTRL_SENSOR_HEIGHT 		IMX219_SENSOR_HEIGHT
#define SENCTRL_SENSOR_CH	 		3

/*
 * DP INP CFG
 *
 * SENSOR --> INP_CROP --> INP_BINNING --> INP_SUBSAMPLE
 *
 * CROP DISABLE: DP_INP_CROP_START_X/DP_INP_CROP_START_Y/DP_INP_CROP_WIDTH/DP_INP_CROP_HEIGHT all 0
 */
#define DP_INP_SUBSAMPLE			INP_SUBSAMPLE_DISABLE
#define DP_INP_BINNING				INP_BINNING_10TO2_B
#define DP_INP_CROP_START_X			0
#define DP_INP_CROP_START_Y			0
#define DP_INP_CROP_WIDTH          	IMX219_INP_CROP_WIDTH
#define DP_INP_CROP_HEIGHT         	IMX219_INP_CROP_HEIGHT
#define DP_INP_OUT_WIDTH 		    IMX219_INP_OUT_WIDTH
#define DP_INP_OUT_HEIGHT 		    IMX219_INP_OUT_HEIGHT


/*
 * DP HW2X2 CFG
 *
 * LIMITATION:
 * 2X2 SUBSAMPLE LT,LB,RT,RBBINNING (WIDTH/2, HEIGHT/2, MIN:2X2, MAX:640X480)
 * 1/3 SUBSAMPLE (WIDTH/3, HEIGHT/3, MIN:3X3, MAX:639X480)
 */
#define DP_HW2X2_PATH				HW2x2_PATH_THROUGH
#define DP_HW2X2_PROCESS_MODE		HW2x2_MODE_UNITY
#define DP_HW2X2_CROP_START_X		0
#define DP_HW2X2_CROP_START_Y		0
#define DP_HW2X2_CROP_WIDTH			DP_INP_OUT_WIDTH
#define DP_HW2X2_CROP_HEIGHT		DP_INP_OUT_HEIGHT
#define DP_HW2X2_ROUND_MODE			HW2x2_ROUNDMODE_FLOOR
#define DP_HW2X2_OUT_WIDTH          (DP_INP_OUT_WIDTH)
#define DP_HW2X2_OUT_HEIGHT         (DP_INP_OUT_HEIGHT)


/*
 * DP CDM CFG
 *
 * LIMITATION:
 * MAX: 480X270
 * MIN: 8X3
 * WIDTH/8
 */
#define DP_CDM_ENABLE				CDM_ENABLE_ON
#define DP_CDM_IN_START_X			0
#define DP_CDM_IN_START_Y			0
#define DP_CDM_IN_WIDTH 			DP_HW2X2_OUT_WIDTH
#define DP_CDM_IN_HEIGHT			DP_HW2X2_OUT_HEIGHT
#define DP_CDM_META_DUMP 			CDM_ENABLE_MATA_DUMP_ON
#define DP_CDM_HT_PACKING 			CDM_ENABLE_HT_PACKING_ON
#define DP_CDM_MIN_ALLOW_DIS 		3
#define DP_CDM_TOLERANCE 			3
#define DP_CDM_REACTANCE 			2
#define DP_CDM_RELAXATION 			1
#define DP_CDM_EROS_TH 				3
#define DP_CDM_NUM_HT_TH 			10
#define DP_CDM_NUM_HT_VECT_TH_X 	8
#define DP_CDM_NUM_HT_VECT_TH_Y 	4
#define DP_CDM_NUM_CONS_HT_BIN_TH_X 1
#define DP_CDM_NUM_CONS_HT_BIN_TH_Y 1
#define DP_CDM_CPU_ACTIVEFLAG 		CDM_CPU_ACTFLAG_SLEEP
#define DP_CDM_INIT_MAP_FLAG 		CDM_INIMAP_FLAG_ON


/*
 * DP HW5X5 CFG
 *
 * LIMITATION:
 * MIN: 8X8
 * WIDTH/8
 * HEIGHT/4
 */
#define DP_HW5X5_PATH				HW5x5_PATH_THROUGH_DEMOSAIC
#define DP_HW5X5_DEMOS_BNDMODE		DEMOS_BNDODE_REFLECT
#define DP_HW5X5_DEMOS_COLORMODE	DEMOS_COLORMODE_YUV420

#if (CIS_MIRROR_SETTING == 0x01)
#define DP_HW5X5_DEMOS_PATTERN		DEMOS_PATTENMODE_GRBG
#elif (CIS_MIRROR_SETTING == 0x02)
#define DP_HW5X5_DEMOS_PATTERN		DEMOS_PATTENMODE_GBRG
#elif (CIS_MIRROR_SETTING == 0x03)
#define DP_HW5X5_DEMOS_PATTERN		DEMOS_PATTENMODE_BGGR
#else
#define DP_HW5X5_DEMOS_PATTERN		DEMOS_PATTENMODE_RGGB
#endif

#define DP_HW5X5_DEMOSLPF_ROUNDMODE DEMOSLPF_ROUNDMODE_FLOOR
#define DP_HW5X5_CROP_START_X 		0
#define DP_HW5X5_CROP_START_Y 		0
#define DP_HW5X5_CROP_WIDTH 		IMX219_HW5x5_CROP_WIDTH
#define DP_HW5X5_CROP_HEIGHT 		IMX219_HW5x5_CROP_HEIGHT
#define DP_HW5X5_OUT_WIDTH 			IMX219_HW5x5_CROP_WIDTH
#define DP_HW5X5_OUT_HEIGHT 		IMX219_HW5x5_CROP_HEIGHT

/*
 * DP JPEG CFG
 *
 * LIMITATION:
 * MAX:640X640
 * MIN: 16X16
 * WIDTH/16
 * HEIGHT/16
 */
#define DP_JPEG_PATH				JPEG_PATH_ENCODER_EN
#define DP_JPEG_ENC_WIDTH 			DP_HW5X5_OUT_WIDTH
#define DP_JPEG_ENC_HEIGHT 			DP_HW5X5_OUT_HEIGHT
#define DP_JPEG_ENCTYPE 			JPEG_ENC_TYPE_YUV420
#define DP_JPEG_ENCQTABLE 			JPEG_ENC_QTABLE_10X

#endif /* APP_SCENARIO_CISDP_CFG_H_ */
