/*
 * app_state.h
 *
 *  Created on: 2022¦~2¤ë21¤é
 *      Author: 902447
 */

#ifndef APP_SCENARIO_APP_FREERTOS_TZ_S_DP_SAMPLE_APP_STATE_H_
#define APP_SCENARIO_APP_FREERTOS_TZ_S_DP_SAMPLE_APP_STATE_H_

/**
 * \struct APP_DP_TASK_STATE_E
 * \brief APP DP TASK STATE
 */
typedef enum
{
	APP_DP_TASK_STATE_UNINIT				=0x0000,
	APP_DP_TASK_STATE_INIT					=0x0001,
	APP_DP_TASK_STATE_SETUP_CAP_START		=0x0002,
	APP_DP_TASK_STATE_SETUP_CAP_END			=0x0003,
	APP_DP_TASK_STATE_RECAP_FRAME			=0x0004,
	APP_DP_TASK_STATE_CAP_FRAMERDY			=0x0005,
	APP_DP_TASK_STATE_STOP_CAP_START		=0x0006,
	APP_DP_TASK_STATE_STOP_CAP_END			=0x0007,
	APP_DP_TASK_STATE_ERROR					,
} APP_DP_TASK_STATE_E;

/**
 * \struct APP_COMM_TASK_STATE_E
 * \brief APP COMM TASK STATE
 */
typedef enum
{
	APP_COMM_TASK_STATE_UNINIT			=0x0000,
	APP_COMM_TASK_STATE_INIT			=0x0001,
	APP_COMM_TASK_STATE_GPIO_INT		=0x0002,
	APP_COMM_TASK_STATE_I2CCOMM			=0x0003,
	APP_COMM_TASK_STATE_ERROR			,
} APP_COMM_TASK_STATE_E;

/**
 * \struct APP_ALGO_TASK_STATE_E
 * \brief APP Algo TASK STATE
 */
typedef enum
{
	APP_ALGO_TASK_STATE_UNINIT				=0x0000,
	APP_ALGO_TASK_STATE_INIT					=0x0001,
	APP_ALGO_TASK_STATE_DOALGO				=0x0002,
	APP_ALGO_TASK_STATE_DOALGO_DONE			=0x0003,
	APP_ALGO_TASK_STATE_STOPALGO				=0x0004,
	APP_ALGO_TASK_STATE_STOPALGO_DONE		=0x0005,
	APP_ALGO_TASK_STATE_ERROR		,
} APP_ALGO_TASK_STATE_E;

/**
 * \struct APP_MAIN_TASK_STATE_E
 * \brief APP MAIN TASK STATE
 */
typedef enum
{
	APP_MAIN_TASK_STATE_UNINIT						=0x0000,
	APP_MAIN_TASK_STATE_INIT						=0x0001,
	APP_MAIN_TASK_STATE_ERROR						,
} APP_MAIN_TASK_STATE_E;

#endif /* APP_SCENARIO_APP_FREERTOS_TZ_S_DP_SAMPLE_APP_STATE_H_ */
