/*
 * app_msg.h
 *
 *  Created on: 2021�~12��15��
 *      Author: 902447
 */

#ifndef APP_SCENARIO_APP_FREERTOS_TZ_S_DP_SAMPLE_APP_MSG_H_
#define APP_SCENARIO_APP_FREERTOS_TZ_S_DP_SAMPLE_APP_MSG_H_

/**
 * \enum CDM_ERROR_E
 * \brief CDM Errors Type
 */
typedef enum
{
	//DP Event Start
	APP_MSG_DPEVENT_ERR_FS_HVSIZE        	=0x0100,  /*!< [8] reg_inpparser_fs_hsize_vsize_error_int_en*/
	APP_MSG_DPEVENT_ERR_FE_TOGGLE        	=0x0101,  /*!< [7] reg_inpparser_wait_fe_toggle_error_int_en*/
	APP_MSG_DPEVENT_ERR_FD_TOGGLE        	=0x0102,	 /*!< [6] reg_inpparser_wait_fd_toggle_error_int_en*/
	APP_MSG_DPEVENT_ERR_FS_TOGGLE      	=0x0103,	 /*!< [5] reg_inpparser_wait_fs_toggle_error_int_en*/
	APP_MSG_DPEVENT_ERR_BLANK_ERR        	=0x0104,  /*!< [4] reg_inpparser_blank_toggle_error_int_en*/
	APP_MSG_DPEVENT_ERR_CRC_ERR        	=0x0105,  /*!< [3] reg_inpparser_crc_error_int_en*/
	APP_MSG_DPEVENT_ERR_FE_ERR        	=0x0106,  /*!< [2] reg_inpparser_fe_cycle_error_int_en*/
	APP_MSG_DPEVENT_ERR_HSIZE_ERR        	=0x0107,  /*!< [1] reg_inpparser_hsize_error_int_en*/
	APP_MSG_DPEVENT_ERR_FS_ERR           	=0x0108,  /*!< [0] reg_inpparser_fs_cycle_error_int_en*/

	APP_MSG_DPEVENT_VSYNC					=0x0109,	/*!< EDM [0]:vsync_active error*/
	APP_MSG_DPEVENT_HSYNC					=0x010A,	/*!< EDM [1]:hsync_active error*/
	APP_MSG_DPEVENT_OVERLAP_VH			=0x010B,	/*!< EDM [2]:overlap_vh error*/
	APP_MSG_DPEVENT_OVERLAP_HD			=0x010C,	/*!< EDM [3]:overlap_hd error*/
	APP_MSG_DPEVENT_OVERLAP_DF			=0x010D,	/*!< EDM [4]:overlap_df error*/
	APP_MSG_DPEVENT_HSYNC_FP				=0x010E,	/*!< EDM [5]:hsync_front_porch error*/
	APP_MSG_DPEVENT_HSYNC_BP				=0x010F,	/*!< EDM [6]:hsync_back_porch error*/
	APP_MSG_DPEVENT_FE					=0x0110,	/*!< EDM [7]:frame_end_timing error*/
	APP_MSG_DPEVENT_CON_VSYNC				=0x0111,	/*!< EDM [8]:con_vsync_active error*/
	APP_MSG_DPEVENT_CON_HSYNC				=0x0112,	/*!< EDM [9]:con_hsync_active error*/
	APP_MSG_DPEVENT_CH0_DE_LESS			=0x0113,	/*!< EDM [10]:ch0_de_less error*/
	APP_MSG_DPEVENT_CH0_DE_MORE			=0x0114,	/*!< EDM [11]:ch0_de_more error*/
	APP_MSG_DPEVENT_CH1_DE_LESS			=0x0115,	/*!< EDM [12]:ch1_de_less error*/
	APP_MSG_DPEVENT_CH1_DE_MORE			=0x0116,	/*!< EDM [13]:ch1_de_more error*/
	APP_MSG_DPEVENT_CH2_DE_LESS			=0x0117,	/*!< EDM [14]:ch2_de_less error*/
	APP_MSG_DPEVENT_CH2_DE_MORE			=0x0118,	/*!< EDM [15]:ch2_de_more error*/
	APP_MSG_DPEVENT_CONV_DE_LESS			=0x0119,	/*!< EDM [16]:con_de_less error*/
	APP_MSG_DPEVENT_CONV_DE_MORE			=0x011A,	/*!< EDM [17]:con_de_more error*/
	APP_MSG_DPEVENT_EDM_WDT3_TIMEOUT		=0x011B,	/*!< EDM WDT3 Timeout*/
	APP_MSG_DPEVENT_EDM_WDT2_TIMEOUT		=0x011C,	/*!< EDM WDT2 Timeout*/
	APP_MSG_DPEVENT_EDM_WDT1_TIMEOUT		=0x011D,	/*!< EDM WDT1 Timeout*/

	APP_MSG_DPEVENT_SENSORCTRL_WDT_OUT	=0x011E,	/*!< Sensor Control Timeout (not used in current code)*/

	APP_MSG_DPEVENT_CDM_FIFO_OVERFLOW		=0x011F,	/*!< CDM Abnormal OVERFLOW*/
	APP_MSG_DPEVENT_CDM_FIFO_UNDERFLOW	=0x0120,	/*!< CDM Abnormal UnderFLOW */

	APP_MSG_DPEVENT_XDMA_WDMA1_ABNORMAL1	=0x0121,	/*!< XDMA_WDMA1STATUS_ERR_FE_COUNT_NOT_REACH */
	APP_MSG_DPEVENT_XDMA_WDMA1_ABNORMAL2	=0x0122,	/*!< XDMA_WDMA1STATUS_ERR_DIS_BEFORE_FINISH */
	APP_MSG_DPEVENT_XDMA_WDMA1_ABNORMAL3	=0x0123,	/*!< XDMA_WDMA1STATUS_ERR_FIFO_CH1_MISMATCH */
	APP_MSG_DPEVENT_XDMA_WDMA1_ABNORMAL4	=0x0124,	/*!< XDMA_WDMA1STATUS_ERR_FIFO_CH2_MISMATCH */
	APP_MSG_DPEVENT_XDMA_WDMA1_ABNORMAL5	=0x0125,	/*!< XDMA_WDMA1STATUS_ERR_FIFO_CH3_MISMATCH*/
	APP_MSG_DPEVENT_XDMA_WDMA1_ABNORMAL6	=0x0126,	/*!< XDMA_WDMA1STATUS_ERR_FIFO_CH1_OVERFLOW */
	APP_MSG_DPEVENT_XDMA_WDMA1_ABNORMAL7	=0x0127,	/*!< XDMA_WDMA1STATUS_ERR_FIFO_CH2_OVERFLOW */
	APP_MSG_DPEVENT_XDMA_WDMA1_ABNORMAL8	=0x0128,	/*!< XDMA_WDMA1STATUS_ERR_FIFO_CH3_OVERFLOW */
	APP_MSG_DPEVENT_XDMA_WDMA1_ABNORMAL9	=0x0129,	/*!< XDMA_WDMA1STATUS_ERR_BUS */

	APP_MSG_DPEVENT_XDMA_WDMA2_ABNORMAL1	=0x012A,	/*!< XDMA_WDMA2STATUS_ERR_FE_COUNT_NOT_REACH */
	APP_MSG_DPEVENT_XDMA_WDMA2_ABNORMAL2	=0x012B,	/*!< XDMA_WDMA2STATUS_ERR_DIS_BEFORE_FINISH */
	APP_MSG_DPEVENT_XDMA_WDMA2_ABNORMAL3	=0x012C,	/*!< XDMA_WDMA2STATUS_ERR_FIFO_MISMATCH */
	APP_MSG_DPEVENT_XDMA_WDMA2_ABNORMAL4	=0x012D,	/*!< XDMA_WDMA2STATUS_ERR_FIFO_OVERFLOW */
	APP_MSG_DPEVENT_XDMA_WDMA2_ABNORMAL5	=0x012E,	/*!< XDMA_WDMA2STATUS_ERR_BUS */
	APP_MSG_DPEVENT_XDMA_WDMA2_ABNORMAL6	=0x012F,	/*!< WDMA2 Abnormal Case6 */
	APP_MSG_DPEVENT_XDMA_WDMA2_ABNORMAL7	=0x0130,	/*!< WDMA2 Abnormal Case7 */

	APP_MSG_DPEVENT_XDMA_WDMA3_ABNORMAL1	=0x0131,	/*!< XDMA_WDMA3STATUS_ERR_FE_COUNT_NOT_REACH */
	APP_MSG_DPEVENT_XDMA_WDMA3_ABNORMAL2	=0x0132,	/*!< XDMA_WDMA3STATUS_ERR_DIS_BEFORE_FINISH */
	APP_MSG_DPEVENT_XDMA_WDMA3_ABNORMAL3	=0x0133,	/*!< XDMA_WDMA3STATUS_ERR_FIFO_CH1_MISMATCH */
	APP_MSG_DPEVENT_XDMA_WDMA3_ABNORMAL4	=0x0134,	/*!< XDMA_WDMA3STATUS_ERR_FIFO_CH2_MISMATCH */
	APP_MSG_DPEVENT_XDMA_WDMA3_ABNORMAL5	=0x0135,	/*!< XDMA_WDMA3STATUS_ERR_FIFO_CH3_MISMATCH */
	APP_MSG_DPEVENT_XDMA_WDMA3_ABNORMAL6	=0x0136,	/*!< XDMA_WDMA3STATUS_ERR_FIFO_CH1_OVERFLOW */
	APP_MSG_DPEVENT_XDMA_WDMA3_ABNORMAL7	=0x0137,	/*!< XDMA_WDMA3STATUS_ERR_FIFO_CH2_OVERFLOW */
	APP_MSG_DPEVENT_XDMA_WDMA3_ABNORMAL8	=0x0138,	/*!< XDMA_WDMA3STATUS_ERR_FIFO_CH3_OVERFLOW */
	APP_MSG_DPEVENT_XDMA_WDMA3_ABNORMAL9	=0x0139,	/*!< XDMA_WDMA3STATUS_ERR_BUS */

	APP_MSG_DPEVENT_XDMA_RDMA_ABNORMAL1	=0x013A,	/*!< XDMA_RDMASTATUS_ERR_DIS_BEFORE_FINISH */
	APP_MSG_DPEVENT_XDMA_RDMA_ABNORMAL2	=0x013B,	/*!< XDMA_RDMASTATUS_ERR_BUS */
	APP_MSG_DPEVENT_XDMA_RDMA_ABNORMAL3	=0x013C,	/*!< RDMA Abnormal Case3 */
	APP_MSG_DPEVENT_XDMA_RDMA_ABNORMAL4	=0x013D,	/*!< RDMA Abnormal Case4 */
	APP_MSG_DPEVENT_XDMA_RDMA_ABNORMAL5	=0x013E,	/*!< RDMA Abnormal Case5 */

	APP_MSG_DPEVENT_CDM_MOTION_DETECT		=0x013F,	/*!< CDM Motion Detect */
	APP_MSG_DPEVENT_XDMA_WDMA1_FINISH		=0x0140,	/*!< xDMA1 WDMA1 FINISH */
	APP_MSG_DPEVENT_XDMA_WDMA2_FINISH		=0x0141,	/*!< xDMA1 WDMA2 FINISH */
	APP_MSG_DPEVENT_XDMA_WDMA3_FINISH		=0x0142,	/*!< xDMA1 WDMA3 FINISH */
	APP_MSG_DPEVENT_XDMA_RDMA_FINISH		=0x0143,	/*!< xDMA1 RDMA FINISH */

	APP_MSG_DPEVENT_XDMA_FRAME_READY		=0x0144,	/*!< xDMA1 Frame Ready by Path*/

	APP_MSG_DPEVENT_TIMER_FIRE_APP_NOTREADY	=0x0145,	/*!< Timer Fire but app not ready for frame */
	APP_MSG_DPEVENT_TIMER_FIRE_APP_READY	=0x0146,	/*!< Timer Fire and app ready for frame */
	APP_MSG_DPEVENT_UNKOWN				    =0x0147,	/*!< DP Unknown */
	APP_MSG_DPEVENT_STARTCAPTURE			=0x0148,	/*!< DP Start Capture */
	APP_MSG_DPEVENT_STOPCAPTURE				=0x0149,	/*!< DP Stop Capture */
	APP_MSG_DPEVENT_RECAPTURE				=0x0150,	/*!< DP Re-Capture */
	APP_MSG_DPEVENT_1BITPARSER_ERR          =0x0151,	/*!< inp1bitparser error */
	//Main Control
	APP_MSG_MAINEVENT_CAP_FRAME_DONE			=0x0200,
	APP_MSG_MAINEVENT_SENSOR_TIMER				=0x0201,
	APP_MSG_MAINEVENT_DP_ERROR					=0x0202,
	APP_MSG_MAINEVENT_SENSOR_DP_ERROR			=0x0203,
	APP_MSG_MAINEVENT_START_CAPTURE			    =0x0204,
	APP_MSG_MAINEVENT_STOP_CAPTURE				=0x0205,
	APP_MSG_MAINEVENT_MOTION_DETECT				=0x0206,
	APP_MSG_MAINEVENT_AON_GPIO0_INT				=0x0207,
	APP_MSG_MAINEVENT_AON_GPIO1_INT				=0x0208,
	APP_MSG_MAINEVENT_SB_GPIO0_INT				=0x0209,
	APP_MSG_MAINEVENT_SB_GPIO1_INT				=0x020A,
	APP_MSG_MAINEVENT_VISIONALGO_STARTDONE		=0x020B,
	APP_MSG_MAINEVENT_VISIONALGO_STOPDONE		=0x020C,
	APP_MSG_MAINEVENT_I2CCOMM					=0x020D,
	APP_MSG_MAINEVENT_AUDIOALGO_STARTDONE		=0x020E,
	APP_MSG_MAINEVENT_AUDIOALGO_STOPDONE		=0x020F,
	APP_MSG_MAINEVENT_VADBUF1_NOTIFY			=0x0210,
	APP_MSG_MAINEVENT_VADBUF2_NOTIFY			=0x0211,
	APP_MSG_MAINEVENT_CM55SRDY_NOTIFY			=0x0212,
	//COMM Control
	APP_MSG_COMMEVENT_AON_GPIO0_INT				=0x0300,
	APP_MSG_COMMEVENT_AON_GPIO1_INT				=0x0301,
	APP_MSG_COMMEVENT_SB_GPIO0_INT				=0x0302,
	APP_MSG_COMMEVENT_SB_GPIO1_INT				=0x0303,
	APP_MSG_COMMEVENT_I2CCOMM_RX				=0x0304,
	APP_MSG_COMMEVENT_I2CCOMM_TX				=0x0305,
	APP_MSG_COMMEVENT_I2CCOMM_ERR				=0x0306,
	APP_MSG_COMMEVENT_SPISEND_PIC				=0x0307,
	//Vision Algo Control
	APP_MSG_VISIONALGOEVENT_START_ALGO			=0x0400,
	APP_MSG_VISIONALGOEVENT_STOP_ALGO			=0x0401,
	APP_MSG_AUDIOALGOEVENT_START_ALGO			=0x0402,
	APP_MSG_AUDIOALGOEVENT_STOP_ALGO			=0x0403,
} APP_MSG_EVENT_E;

/**
 * \struct APP_MSG_T
 * \brief APP MSG
 */
typedef struct
{
	APP_MSG_EVENT_E  msg_event;				/*!< MSG E */
	uint32_t msg_data;				/*!< message data*/
} APP_MSG_T;

#endif /* APP_SCENARIO_APP_FREERTOS_TZ_S_DP_SAMPLE_APP_MSG_H_ */
