name: Check and Pull Upstream Updates

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # Runs each day UTC midnight
  workflow_dispatch:

jobs:
  update-upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name 'Automatic upstream updater'
        git config --global user.email 'tobynpacker@gmail.com'

    - name: Fetch upstream
      run: git fetch https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2.git main:upstream/main

    - name: Check if merge is possible
      id: merge_check
      run: |
        if git merge-base --is-ancestor upstream/main main; then
          echo "merge_status=up_to_date" >> $GITHUB_OUTPUT
        elif git merge-tree $(git merge-base upstream/main main) main upstream/main | grep -q "^<<<<<<< "; then
          echo "merge_status=conflict" >> $GITHUB_OUTPUT
        else
          echo "merge_status=can_merge" >> $GITHUB_OUTPUT
        fi

    - name: Merge upstream main into current branch
      if: steps.merge_check.outputs.merge_status == 'can_merge'
      run: |
        git merge upstream/main --allow-unrelated-histories -m "Merge upstream changes"

    - name: Push changes to origin
      if: steps.merge_check.outputs.merge_status == 'can_merge'
      run: git push origin main

    - name: Handle conflicts or up-to-date scenario
      if: steps.merge_check.outputs.merge_status != 'can_merge'
      run: |
        if [ "${{ steps.merge_check.outputs.merge_status }}" = "conflict" ]; then
          echo "Merge conflicts detected. Manual intervention required."
          exit 1
        else
          echo "Already up to date with upstream."
        fi
